"""command association table

Revision ID: c3ffce09bf2b
Revises: f08a408ddee1
Create Date: 2018-04-15 14:30:30.539760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ffce09bf2b'
down_revision = 'f08a408ddee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=64), nullable=True),
    sa.Column('script_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_type_keyword'), 'command_type', ['keyword'], unique=True)
    op.create_index(op.f('ix_command_type_script_name'), 'command_type', ['script_name'], unique=True)
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['command'], ['command_type.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command')
    op.drop_index(op.f('ix_command_type_script_name'), table_name='command_type')
    op.drop_index(op.f('ix_command_type_keyword'), table_name='command_type')
    op.drop_table('command_type')
    # ### end Alembic commands ###
