"""command timestamp

Revision ID: fec9f3550d65
Revises: c3ffce09bf2b
Create Date: 2018-04-15 14:38:07.398638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec9f3550d65'
down_revision = 'c3ffce09bf2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_command_timestamp'), 'command', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_timestamp'), table_name='command')
    op.drop_column('command', 'timestamp')
    # ### end Alembic commands ###
